#!/bin/sh

printf "\nCOMMAND ARGUMENTS:\n"

printf "\npmt2e [--desktop] | [--bbswitch] | [--volume] | [--brightness] | [--lbrightness] | [--battery] | [--wifi] | [--zslider] [menu]\n\n"

printf "Arguments to execute actions | format display:\n\n"

echo "--desktop [next] | [prev] | [<number>] [-N]"
echo "--bbswitch [-N]"
echo "--volume [up] | [down] | [<level>] [-N]"
echo "--brightness [up] | [down] | [<level>] [-N]"
echo "--lbrightness [up] | [down] | [<level>] [-N]"
echo "--yad [bri] | [vol] - displays a slider to set volume | brightness level"
echo "--battery [-c [-l]] | [-n] | [-F] | [-N]"
echo "--wifi [-N] | [-M'custom name']"
echo "--update -C[aur_helper] | -U<terminal>[:aur_helper] | [-O] [-N] | [-M<custom_name>] | [-h] | [--help]"
echo "--weather [-I<items>] [-A<api_key>] [-C<city_id>] [-U<units>] [-L<lang>] | [-D[<city_id>]] | [-h] | [--help]"
echo "--paswitch - displays jgmenu to switch audio output."
echo -e "\n[menu] argument after --command displays context menu (if jgmenu package is installed). Edit templates in ~/.t2ecol folder to customize menus."
echo -e "\n[-N] - displays (N)ame instead of icon in tint2 panel. Uncheck 'Show icon' in executor!"
echo -e "\n[-M]<custom_name> - print custom na(M)e instead of icon."
echo -e "\n[-F] - show icon as font glyphs. Uncheck 'Show icon' and add a 4 pixel space (8 for weather) in 'Horizontal Padding in executor!"
echo -e "\n[-n] - in --battery command show a notification displaying current battery status."
echo -e "\n[-l] - appends battery level percentage to the icon."
echo -e "\nwithout argument --battery command updates current icon, shows a notification and plays an audio alert if battery is under 5%.\n"
echo -e "\nDependencies:"
echo "xbacklight package for --brightness"
echo "light package for --lbrightness"
echo "yad alsa-utils [xbacklight | light] for --yad"
echo "dunst vorbis-tools sound-theme-freedesktop for --battery"
echo "python pacman-contrib for --update"
echo "python wmctrl for --desktop"
echo "wireless-tools for --wifi"
echo "python pulseaudio pulseaudio-alsa for --paswitch"
echo "python wget dunst for --weather"
echo "nvidia-utils for --bbswitch"
echo -e "\nOptional dependencies:"
echo "jgmenu for menus"
echo "[pacaur | trizen | yay] for --update"
echo -e "A Nerd Font of your choice to show icon using font glyphs\n"

